_base_config: config/pretrain/nuscenes/slidr/slidr_moco.yaml

model:
  image:
    # return pretrained image features for computing similarity between superpixels
    return_pretrain_feat: True

criteria:
  NCE_temperature: 0.07
  losses:
    enabled: ["loss_superpixel_stslidr"]
    params:
      loss_superpixel_stslidr:
        min_quantile: 0.01 # percentage of negatives to drop
